port=53

listen-address=127.0.0.1,10.7.2.83
bind-interfaces

address=/app.dimaginaxal.test/10.7.1.138
address=/api.dimaginaxal.test/10.7.1.138

no-resolv
server=1.1.1.1
server=8.8.8.8

cache-size=1000
